// Per-session state every layer reads: the routes answering /api/sessions, the WebSocket
// handlers, the Claude hooks, and the PTY spawns all reach for the same tables. They lived
// in index.ts, which is why nothing else could be split out of it (#548) — a table here can
// be imported without importing the boot module.
//
// The maps are exported directly, not behind accessors: every call site already reads and
// writes them as maps, and wrapping ~150 of those in getters would be churn with no invariant
// to enforce. What DOES belong here is the persistence, because "what is on disk" and "what
// is in memory" have to agree.
import { promises as fs } from "node:fs";
import path from "node:path";
import { MULMOTERMINAL_HOME, SESSION_ID_RE } from "../config/env.js";
import { messageOf } from "../errors.js";
import { buildActivitySnapshot, mergeOwnedActivity, parseActivityState, type PersistedActivity } from "./activity-state.js";
import { parseSessionIdLog, sessionIdLogLine } from "./session-id-log.js";
import {
  antigravityConversationLine,
  antigravityConversationRecord,
  applyAntigravityConversation,
  hydrateAntigravityConversationInto,
  type AntigravityConversation,
} from "./antigravity-conversations.js";
import { applySessionMemo, createMemoWriteGuard, sessionMemoLine, sessionMemoRecord } from "./session-memos.js";
import { normalizeMemo } from "../../common/sessionMemo.js";
import { forEachJsonlRecord } from "../infra/jsonl-file.js";
import { parseSessionToolGroups, sessionToolGroupLine, TOOL_GROUP_RESET, type SessionToolGroup } from "./session-tool-groups.js";
import type { ToolGroup } from "../../common/toolGroups.js";
import type { Activity, PtyEntry } from "./types.js";

// Per-session "working" state, driven by Claude hooks (see /api/hook):
// UserPromptSubmit => Claude started thinking; Stop => it finished.
export const activity = new Map<string, Activity>(); // id -> { working, event, at }

// Live ptys keyed by session id. A pty outlives its WebSocket while the session
// is still "working", so switching away doesn't interrupt Claude mid-turn; it
// is reaped once the session goes idle (Stop hook) or the process exits. `ws`
// is null while the session runs in the background.
export const ptys = new Map<string, PtyEntry>(); // id -> { term, ws, buffer }

// Latest MEANINGFUL user prompt per session (from the UserPromptSubmit hook), shown
// on the grid cell header so you can tell at a glance what each terminal is about. A
// trivial ack ("ok", "merge") doesn't replace it (see the hook handler), so a short
// follow-up can't hide the task.
export const lastPrompts = new Map<string, string>(); // id -> prompt text

// AI header title per session (issue #316): a short summary of the recent turns that
// stays meaningful when the session turns into a back-and-forth, where the raw last
// prompt goes stale ("ok") or context-dependent ("2番目にして"). Generated by a cheap
// model, it takes precedence over lastPrompt in the cell header. Kept in memory (never
// written into Claude's transcript); a resumed session falls back to any on-disk title.
// the last few lines of the agent's most recent reply, refreshed when
// a turn ends (waiting), so the roster can show "what it just said" without the terminal open.
export const lastResponses = new Map<string, string>(); // id -> last assistant text (truncated)

export const titleTurnCounts = new Map<string, number>(); // id -> user turns since last title
export const titlePending = new Set<string>(); // ids whose next Stop should (re)generate a title
export const titleInFlight = new Set<string>(); // ids currently generating, to avoid overlap
export const titleEpoch = new Map<string, number>(); // bumped on /clear or teardown to void an in-flight generation
// The transcript's user-turn count when we last titled a session, so the roster's view-triggered
// re-titling knows when a session has advanced enough to be worth re-summarizing. Kept across
// /clear (dropped only on teardown) so a just-cleared session isn't re-titled from its frozen
// pre-clear transcript.
export const lastTitledUserTurns = new Map<string, number>();
// Wall-clock of the last view-triggered title attempt per session, so a session whose generation
// keeps failing backs off instead of re-spawning the summarizer on every 4s roster poll.
export const lastTitleAttemptMs = new Map<string, number>();

const isValidSessionId = (id: string) => SESSION_ID_RE.test(id);

// mulmoterminal session key -> the codex rollout id it maps to. codex mints its own id, so we
// discover it after spawn and keep it here to `codex resume <id>` once the live PTY is gone.
// This mapping is NOT a list source: mobile/session pickers still have to start from live/tmux,
// dev-terminal/activity, or an explicitly cwd-scoped query. That keeps old rollout history from
// flooding the UI while preserving the one fact needed to title/resume a session the UI already
// has another reason to care about.
//
// Append-only like the other session id logs in this file. It can retain mappings for old sessions,
// but those do not create mobile rows by themselves; they are consulted only after another bounded
// source has already selected the MulmoTerminal session id.
export const codexRolloutIds = new Map<string, string>();
const CODEX_ROLLOUT_IDS_FILE = path.join(MULMOTERMINAL_HOME, "codex-rollout-ids.log");
export const codexRolloutIdsHydrated = (async () => {
  try {
    for (const line of (await fs.readFile(CODEX_ROLLOUT_IDS_FILE, "utf8")).split("\n")) {
      const [id, rolloutId] = line.trim().split(/\s+/);
      if (id && rolloutId && isValidSessionId(id) && isValidSessionId(rolloutId)) codexRolloutIds.set(id, rolloutId);
    }
  } catch {
    // absent on first run / unreadable => no mappings remembered
  }
})();
let codexRolloutPersist: Promise<void> = Promise.resolve();
function appendCodexRolloutId(id: string, rolloutId: string): void {
  codexRolloutPersist = codexRolloutPersist
    .then(() => fs.mkdir(MULMOTERMINAL_HOME, { recursive: true }))
    .then(() => fs.appendFile(CODEX_ROLLOUT_IDS_FILE, `\n${id} ${rolloutId}`))
    .catch((e) => console.error(`[codex-rollout-ids] failed to persist: ${messageOf(e)}`));
}

export function rememberCodexRolloutId(id: string, rolloutId: string): void {
  if (!isValidSessionId(id) || !isValidSessionId(rolloutId) || codexRolloutIds.get(id) === rolloutId) return;
  codexRolloutIds.set(id, rolloutId);
  appendCodexRolloutId(id, rolloutId);
}
// Rollout files already attributed to a session, so a single rollout is never mapped to two keys
// (which would let both cold-resume the same conversation). Serialized by the single event loop.
export const claimedCodexRollouts = new Set<string>();

// Sessions spawned with our `--settings` hooks, i.e. the ones that report their own tool calls to
// /api/hook. Only spawn-claude registers them, because only claude has a hook mechanism.
//
// It exists so the MCP broker can tell whether a session's tool calls are ALREADY being recorded,
// without asking what agent it is: a codex launcher chip runs codex through the login shell, so
// its PtyEntry is honestly labelled "shell" and no agent name identifies it (see
// mcp/gui-call-history.ts). What the broker actually needs to know is this, not the name.
//
// Never pruned. An id is a v4 uuid used once, the set costs a string per session, and forgetting
// one would silently start double-recording that session's GUI calls — the opposite of cheap.
export const hookedSessions = new Set<string>();

// Conversation directories already attributed to a session, so one is never mapped to two keys
// (which would let both cold-resume the same conversation). The session -> conversation mapping
// itself is persisted; see `antigravityConversations` below.
export const claimedAntigravityConversations = new Set<string>();

// Hidden translation-worker sessions run in CLAUDE_CWD — the workspace the user has
// already trusted — because claude blocks on its workspace-trust dialog in any
// untrusted dir (no input ever comes, so the worker would hang). Their session ids
// are tracked here so they're FILTERED OUT of /api/sessions: a translation worker is
// a transient internal helper, not a chat the user should see in the sidebar.

// Hydrate one id log once at boot (best-effort — absent on first run / unreadable => empty).
// Exposed as a promise so readers/writers can wait for it: a request served (or a mark
// persisted) before this resolves would otherwise see an empty set and either leak the
// sessions the log exists to keep out or clobber the file with a snapshot missing the
// on-disk ids.
function hydrateIdLog(file: string, into: Set<string>): Promise<void> {
  return (async () => {
    try {
      for (const id of parseSessionIdLog(await fs.readFile(file, "utf8"), isValidSessionId)) into.add(id);
    } catch {
      // absent on first run / unreadable => nothing remembered
    }
  })();
}

// Appended, never rewritten: another instance shares these files, and a read-merge-write
// loses whichever of the two finishes first however small the window is made. An append
// needs no read, and nothing here is ever removed. Each log gets its own chain so its
// writes stay ordered and a failure is logged without stopping the next one.
function idLogAppender(file: string, label: string): (id: string) => void {
  let persist: Promise<void> = Promise.resolve();
  return (id: string) => {
    persist = persist
      .then(() => fs.mkdir(MULMOTERMINAL_HOME, { recursive: true }))
      .then(() => fs.appendFile(file, sessionIdLogLine(id)))
      .catch((e) => console.error(`[${label}] failed to persist: ${messageOf(e)}`));
  };
}

// Sessions that connected on the ALL-TOOLS MCP url (`/api/mcp/:sessionId`). That url is handed
// out by --mcp-config and by nothing else, so reaching it is proof the session carries the whole
// GUI MCP — including the tools that belong to no group and are therefore unreachable through a
// group url (spawnBackgroundChat).
//
// Recorded as its own fact rather than inferred from "has all four groups", which is a different
// statement: a directory that registered every group url really does have all four groups and
// really does NOT have the ungrouped tools.
//
// Persisted for the same reason the tool-group log is: the learning happens in memory, and a
// server restart would forget it while the claude process keeps running in tmux, already past
// the ListTools that would teach us again.
const allToolsSessions = new Set<string>();
const ALL_TOOLS_SESSIONS_FILE = path.join(MULMOTERMINAL_HOME, "all-tools-sessions.json");
export const allToolsSessionsHydrated = hydrateIdLog(ALL_TOOLS_SESSIONS_FILE, allToolsSessions);
const appendAllToolsSession = idLogAppender(ALL_TOOLS_SESSIONS_FILE, "all-tools-sessions");

/** Note that a session reached us on the all-tools url. A no-op once known — one server is built
 *  per MCP request, so this is asked on every tool call. */
export function markAllToolsSession(id: string): void {
  if (!isValidSessionId(id) || allToolsSessions.has(id)) return;
  allToolsSessions.add(id);
  appendAllToolsSession(id);
}

/** Does this session carry the whole GUI MCP, rather than the subset its directory registered? */
export function hasAllGuiTools(id: string): boolean {
  return allToolsSessions.has(id);
}

// Visibility metadata for transcript/history rows after their Core membership has been
// explicitly deleted. This never contributes Terminal membership or classifies a live session;
// live visibility comes only from Core metadata. The filename is retained to upgrade existing
// installations without losing the history classification they already recorded.
const backgroundHistoryIds = new Set<string>();
const BACKGROUND_HISTORY_FILE = path.join(MULMOTERMINAL_HOME, "background-sessions.json");
export const backgroundHistoryHydrated = hydrateIdLog(BACKGROUND_HISTORY_FILE, backgroundHistoryIds);
const appendBackgroundHistory = idLogAppender(BACKGROUND_HISTORY_FILE, "background-history");

export function markBackgroundHistory(id: string): void {
  if (!isValidSessionId(id) || backgroundHistoryIds.has(id)) return;
  backgroundHistoryIds.add(id);
  appendBackgroundHistory(id);
}

export function isBackgroundHistory(id: string): boolean {
  return backgroundHistoryIds.has(id);
}

// Sessions the SCHEDULER started — a user's own configured task, as opposed to a collection
// refresh or an internal helper.
//
// They are background sessions in every other respect (out of the chat list, never bold, no grid
// cell), and this exists because ONE of those respects is wrong for them: a turn ending on a
// background session never reaches the phone, on the reasoning that it "isn't a real user task".
// A task the user configured to run while they are away is exactly a real user task, and push is
// the only way they would ever hear about it (Codex, PR #1196).
//
// Persisted like its siblings: a tmux session outlives a server restart, so the turn that raises
// the push can happen long after the process that spawned it is gone.
const userScheduledSessions = new Set<string>();
const USER_SCHEDULED_SESSIONS_FILE = path.join(MULMOTERMINAL_HOME, "user-scheduled-sessions.json");
export const userScheduledSessionsHydrated = hydrateIdLog(USER_SCHEDULED_SESSIONS_FILE, userScheduledSessions);
const appendUserScheduledSession = idLogAppender(USER_SCHEDULED_SESSIONS_FILE, "user-scheduled-sessions");

export function markUserScheduledSession(id: string): void {
  if (!isValidSessionId(id) || userScheduledSessions.has(id)) return;
  userScheduledSessions.add(id);
  appendUserScheduledSession(id);
}

/** Did the scheduler start this? Asked by the push rules, which suppress background sessions. */
export function isUserScheduledSession(id: string): boolean {
  return userScheduledSessions.has(id);
}

// Background workers whose run ENDED BADLY: reached teardown without ever reporting a finished
// turn. A worker is invisible on purpose, so a failed one is the single case where that design
// works against the user — nothing pulls their attention and nothing is waiting to be clicked, so
// without a record the failure is simply never learned.
//
// Persisted for the same reason the set above is, and more so: the whole value of this is being
// able to find out LATER. A live-only flag would be cleared by the very reap that discovers the
// failure.
const failedWorkers = new Set<string>();
const FAILED_WORKERS_FILE = path.join(MULMOTERMINAL_HOME, "failed-workers.json");
export const failedWorkersHydrated = hydrateIdLog(FAILED_WORKERS_FILE, failedWorkers);
const appendFailedWorker = idLogAppender(FAILED_WORKERS_FILE, "failed-workers");

/** Record that a background worker ended without succeeding. Only ever called for a session that
 *  is already a background one — a watched session's failure is visible in its own terminal. */
export function markFailedWorker(id: string): void {
  if (!isValidSessionId(id) || failedWorkers.has(id)) return;
  failedWorkers.add(id);
  appendFailedWorker(id);
}

/** Did this background worker end badly? Read per row by the session list, so a launcher can say
 *  so next to the worker rather than making the user open each one to find out. */
export function isFailedWorker(id: string): boolean {
  return failedWorkers.has(id);
}

// Where each grid session was started, for the sessions this process did not spawn (#1021). Live
// ones answer from `ptys`, which is the truer source — it knows where claude actually runs.
// Which agy conversation each antigravity session runs, so a cold reconnect can resume it with
// `--conversation <id>`. Persisted because agy mints the id and we discover it after the spawn: a
// map that dies with the process leaves the conversation on disk with nothing pointing at it.
export const antigravityConversations = new Map<string, AntigravityConversation>();
const ANTIGRAVITY_CONVERSATIONS_FILE = path.join(MULMOTERMINAL_HOME, "antigravity-conversations.jsonl");

// Sessions this process has already recorded. Hydration reads the file as it was BEFORE our append
// could reach it, so without this a session spawned during startup is overwritten by an older line
// — and the cwd it answers with would be the directory that session used to run in.
const antigravityWrittenIds = new Set<string>();

export const antigravityConversationsHydrated: Promise<void> = (async () => {
  try {
    // Streamed rather than read whole: one line per antigravity spawn, and nothing prunes it.
    await forEachJsonlRecord(ANTIGRAVITY_CONVERSATIONS_FILE, (parsed) => {
      const record = antigravityConversationRecord(parsed, isValidSessionId);
      if (record) hydrateAntigravityConversationInto(antigravityConversations, antigravityWrittenIds, record);
    });
  } catch {
    // absent on first run / unreadable => nothing to resume, which is today's behaviour anyway
  }
})();

let antigravityPersist: Promise<void> = Promise.resolve();

/** Map a session to the agy conversation it is running, and persist it. */
export function rememberAntigravityConversation(sessionId: string, conversationId: string, cwd: string): void {
  if (!isValidSessionId(sessionId) || !isValidSessionId(conversationId) || !cwd) return;
  const known = antigravityConversations.get(sessionId);
  if (known?.conversationId === conversationId && known.cwd === cwd) return; // already the answer; appending would only grow the log
  // Carried over rather than re-stamped: a session relaunched somewhere else appends a second
  // line, and taking the clock there would make `startedAt` mean "last written", which is not
  // what a reader sorting by it would get. The first line for a session is written at its spawn.
  const record: AntigravityConversation = { sessionId, conversationId, cwd, startedAt: known?.startedAt ?? Date.now() };
  antigravityWrittenIds.add(sessionId);
  applyAntigravityConversation(antigravityConversations, record);
  antigravityPersist = antigravityPersist
    .then(() => fs.mkdir(MULMOTERMINAL_HOME, { recursive: true }))
    .then(() => fs.appendFile(ANTIGRAVITY_CONVERSATIONS_FILE, antigravityConversationLine(record)))
    .catch((e) => console.error(`[antigravity-conversations] failed to persist: ${messageOf(e)}`));
}

// UI and conversation auxiliary state below never establishes terminal membership. Core is the
// only authority for whether a terminal session exists.
// History-owned one-line notes for conversations with no Core membership. Live Session memos
// live only in Core metadata; this store never supplies or mirrors a live memo.
export const sessionMemos = new Map<string, string>();
const SESSION_MEMOS_FILE = path.join(MULMOTERMINAL_HOME, "session-memos.jsonl");

// Ids this process has already written. Hydration reads the file as it was BEFORE our append
// could reach it, so without this an edit made during startup is overwritten by the old value —
// and an ERASE has no map entry to notice, so the erased memo would come back from the dead.
const memoWrittenIds = new Set<string>();

export const sessionMemosHydrated: Promise<void> = (async () => {
  try {
    // Streamed rather than read whole: nothing caps this file, since it grows for as long as the
    // user keeps editing memos.
    await forEachJsonlRecord(SESSION_MEMOS_FILE, (parsed) => {
      const record = sessionMemoRecord(parsed, isValidSessionId);
      if (record && !memoWrittenIds.has(record.id)) applySessionMemo(sessionMemos, record);
    });
  } catch {
    // absent on first run / unreadable => no memos, which is how every session starts anyway
  }
})();

/** Copy notes for still-live legacy ids into Core once. The history store remains the owner only
 * for ids without membership; individual delete races are isolated from server startup. */
export async function migrateHistoryMemosToCore(
  sessions: readonly { id: string; memo: string | null }[],
  setCoreMemo: (id: string, memo: string) => Promise<void>,
): Promise<number> {
  await sessionMemosHydrated;
  const candidates = sessions.flatMap((session) => {
    const memo = sessionMemos.get(session.id);
    return !session.memo && memo ? [{ id: session.id, memo }] : [];
  });
  const migrated = await Promise.allSettled(candidates.map(({ id, memo }) => setCoreMemo(id, memo)));
  return migrated.filter((result) => result.status === "fulfilled").length;
}

/** Transfer a live note to its history owner immediately before explicit Core deletion.
 * This is a one-time ownership handoff, never a live metadata mirror. */
export async function handoffCoreMemoToHistory(session: { id: string; memo: string | null; resumeSource: string | null }): Promise<void> {
  if (!session.memo) return;
  await setSessionMemo(session.resumeSource ?? session.id, session.memo);
}

let memoPersist: Promise<void> = Promise.resolve();
const memoWrites = createMemoWriteGuard();

/**
 * Store a session's memo, or erase it when the text normalizes to empty. Resolves to what was
 * stored — the store's answer, not the request's — once the append is ON DISK.
 *
 * AWAITED, unlike the fire-and-forget appenders above, and the difference is what is being
 * written: a cwd or an id is derived state this server can work out again, while a memo is a
 * sentence the user typed and nothing can reconstruct. So a failed write REJECTS and puts the
 * previous value back, rather than logging and leaving a note on screen that is not saved
 * anywhere and vanishes at the next restart (CodeRabbit).
 */
export async function setSessionMemo(id: string, text: string): Promise<string> {
  const memo = normalizeMemo(text);
  if (!isValidSessionId(id)) return memo;
  const previous = sessionMemos.get(id);
  const ticket = memoWrites.begin(id);
  memoWrittenIds.add(id);
  applySessionMemo(sessionMemos, { id, text: memo });
  const append = memoPersist
    .then(() => fs.mkdir(MULMOTERMINAL_HOME, { recursive: true }))
    .then(() => fs.appendFile(SESSION_MEMOS_FILE, sessionMemoLine(id, memo, Date.now())));
  // The CHAIN must survive this write failing — it is what serializes the appends, and a rejected
  // promise left in it would take down every memo written afterwards.
  memoPersist = append.catch(() => {});
  try {
    await append;
  } catch (e) {
    // Only while this is still the newest write for the id. Matching on the VALUE instead would
    // roll back over a later write that carried the same text and succeeded — leaving this process
    // serving the old note while the disk holds the new one (Codex).
    if (memoWrites.isLatest(id, ticket)) applySessionMemo(sessionMemos, { id, text: previous ?? "" });
    throw new Error(`failed to persist the memo: ${messageOf(e)}`, { cause: e });
  }
  return memo;
}

// Which GUI tool groups a session actually has. Learned from the group URLs it connects to
// (see session-tool-groups.ts) rather than configured here — a grid cell's GUI tools come
// from the user's own per-folder MCP config, which we do not read. Read it through
// sessionToolGroups() so callers can't mutate the stored set.
const toolGroupsBySession = new Map<string, Set<ToolGroup>>();
const SESSION_TOOL_GROUPS_FILE = path.join(MULMOTERMINAL_HOME, "session-tool-groups.json");

async function readPersistedToolGroups(): Promise<SessionToolGroup[]> {
  try {
    return parseSessionToolGroups(await fs.readFile(SESSION_TOOL_GROUPS_FILE, "utf8"), isValidSessionId);
  } catch {
    return [];
  }
}

// Ids a spawn has already superseded this process. Hydration reads the log as it was BEFORE
// that spawn's reset marker could be appended, so without this it would put the old groups
// back — the reset would win in the file and lose in memory.
const resetToolGroupSessions = new Set<string>();

export const sessionToolGroupsHydrated: Promise<void> = (async () => {
  for (const { sessionId, group } of await readPersistedToolGroups()) {
    if (resetToolGroupSessions.has(sessionId)) continue;
    addToolGroupInMemory(sessionId, group);
  }
})();

let toolGroupsPersist: Promise<void> = Promise.resolve();
function appendSessionToolGroup(sessionId: string, group: ToolGroup): void {
  toolGroupsPersist = toolGroupsPersist
    .then(() => fs.mkdir(MULMOTERMINAL_HOME, { recursive: true }))
    .then(() => fs.appendFile(SESSION_TOOL_GROUPS_FILE, sessionToolGroupLine(sessionId, group)))
    .catch((e) => console.error(`[session-tool-groups] failed to persist: ${messageOf(e)}`));
}

function addToolGroupInMemory(sessionId: string, group: ToolGroup): boolean {
  const groups = toolGroupsBySession.get(sessionId) ?? new Set<ToolGroup>();
  if (groups.has(group)) return false;
  groups.add(group);
  toolGroupsBySession.set(sessionId, groups);
  return true;
}

// Note that a session reached us on a group's URL, then persist. A no-op once known, so the
// per-request MCP calls (one server is built per request) don't append on every tool call.
export function markSessionToolGroup(sessionId: string, group: ToolGroup): void {
  if (!SESSION_ID_RE.test(sessionId)) return;
  if (addToolGroupInMemory(sessionId, group)) appendSessionToolGroup(sessionId, group);
}

export function sessionToolGroups(sessionId: string): ToolGroup[] {
  return [...(toolGroupsBySession.get(sessionId) ?? [])];
}

/** Settles once every persist queued so far has hit the disk.
 *
 *  The appends above are deliberately fire-and-forget — a tool call must not wait on a log — but
 *  that leaves no way to know they are done, and each one begins with `mkdir(…, recursive)`. A
 *  caller that deletes the home directory before the queue drains has it RECREATED underneath it,
 *  which is how a spec pointing HOME at a temp directory left one behind on every single run
 *  (#1345). Awaiting this before cleaning up is what makes that deterministic. */
export const whenToolGroupsPersisted = (): Promise<void> => toolGroupsPersist;

// Forget what a session had, because it is being replaced. Called on every claude spawn for the
// id: the new process gets whatever the user's MCP config says NOW, so carrying the old answer
// forward would keep asserting a capability the user may have just switched off. The marker is
// appended rather than the file rewritten, for the same reason nothing else here is rewritten.
// UNCONDITIONAL, and that is the point. Skipping the marker when the in-memory set looks empty
// was wrong twice over on a resume at boot: hydration may not have run yet, so "empty" means
// "not read yet" rather than "nothing there" — and the marker is the only thing that survives to
// the NEXT restart, where a process-local memo would be gone and the log replayed from scratch.
// One line per claude spawn, in a file that already grows per learned group.
export function resetSessionToolGroups(sessionId: string): void {
  if (!SESSION_ID_RE.test(sessionId)) return;
  // Both flags set synchronously, before any await: a read landing between here and the append
  // must not see the replaced process's capabilities, and hydration must not restore them.
  resetToolGroupSessions.add(sessionId);
  toolGroupsBySession.set(sessionId, new Set());
  toolGroupsPersist = toolGroupsPersist
    .then(() => fs.mkdir(MULMOTERMINAL_HOME, { recursive: true }))
    .then(() => fs.appendFile(SESSION_TOOL_GROUPS_FILE, sessionToolGroupLine(sessionId, TOOL_GROUP_RESET)))
    .catch((e) => console.error(`[session-tool-groups] failed to persist reset: ${messageOf(e)}`));
}

// Restore the `working` + blocked/done (`waiting`) flags across a server restart (e.g. a
// --watch hot reload), so a live session doesn't reattach as idle. `waiting` matters because
// Claude won't re-fire Notification while already sitting at a prompt; `working` because a
// turn usually outlives the ~1s restart and its later Stop hook self-corrects a stale flag
// (the only stale case is a turn that finished DURING the restart window — corrected on the
// user's next turn). Read paths await hydration (see /api/activity, /api/session) so a
// reconnect re-fetch can't race it back to idle. Mirrors the dev-terminal-sessions pattern.
const ACTIVITY_STATE_FILE = path.join(MULMOTERMINAL_HOME, "activity-state.json");
export const activityStateHydrated: Promise<void> = (async () => {
  try {
    const parsed: unknown = JSON.parse(await fs.readFile(ACTIVITY_STATE_FILE, "utf8"));
    for (const { id, working, waiting, event } of parseActivityState(parsed, (x) => SESSION_ID_RE.test(x))) {
      // Don't clobber a live update that already landed while hydration was in flight.
      if (!activity.has(id)) activity.set(id, { working, waiting, event, at: Date.now() });
    }
  } catch {
    // no file yet / unreadable => nothing to restore
  }
})();

// The sessions THIS process drives (every id it has flagged working/waiting). The file is
// shared with any other server rooted at the same MULMOTERMINAL_HOME, and hydration pulls the
// other instance's ids into `activity` too — so a snapshot of the whole map is not this
// instance's to write back. Ownership is claimed on the flag, not derived from `ptys`, so a
// just-reaped session (pty already gone) is still recognised as ours and removed from the file.
const ownedActivityIds = new Set<string>();
export function claimActivityOwnership(id: string): void {
  ownedActivityIds.add(id);
}

async function readPersistedActivity(): Promise<Record<string, PersistedActivity>> {
  try {
    const parsed = parseActivityState(JSON.parse(await fs.readFile(ACTIVITY_STATE_FILE, "utf8")), (x) => SESSION_ID_RE.test(x));
    return Object.fromEntries(parsed.map(({ id, working, waiting, event }) => [id, { working, waiting, event }]));
  } catch {
    return {}; // no file yet / unreadable => nothing to preserve
  }
}

// Serialize writes into one chain (like appendDevTerminalSession). Read the current file and
// rewrite only the entries THIS instance owns, so a second instance's sessions are neither
// dropped nor revived.
let activityPersist: Promise<void> = Promise.resolve();
export function persistActivityState(): void {
  activityPersist = activityPersist
    .then(() => activityStateHydrated)
    .then(() => fs.mkdir(MULMOTERMINAL_HOME, { recursive: true }))
    .then(async () => {
      const onDisk = await readPersistedActivity();
      const owned = buildActivitySnapshot(
        [...activity].filter(([id]) => ownedActivityIds.has(id)),
        () => false,
      );
      const next = mergeOwnedActivity(onDisk, owned, (id) => ownedActivityIds.has(id));
      await fs.writeFile(ACTIVITY_STATE_FILE, JSON.stringify(next));
    })
    .catch((e) => console.error(`[activity-state] failed to persist: ${messageOf(e)}`));
}
